# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
