# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 11:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('articles', '0002_commonuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonuser',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='CommonUser',
        ),
    ]
