# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 11:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='avatar/default_avatar.jpg', upload_to='')),
                ('mysite', models.CharField(max_length=255, null=True)),
                ('career', models.CharField(max_length=255, null=True)),
                ('introduction', models.TextField(max_length=3000, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Common users',
                'verbose_name': 'Common user',
            },
        ),
    ]
